### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/rupesh/rupesh/colabfold/SSR1_type1/7_GP4/7/SignalP4_7.csv'

### ISSUE THREAD

**Issue by rupesh-sinha** [grassoste/GP4_standalone#1]
Hi,
I am trying to using GP4 for predicting subcellular location of a Gram positive bacterial protein. All the prerequisite programs were downloaded and paths were set at conf.env and the ./GP4.py -h run well, but when I ma trying to run it on a .fasta file following error generated.
  
python GP4.py --input /home/rupesh/rupesh/colabfold/SSR1_type1/7.fasta -o /home/rupesh/rupesh/colabfold/SSR1_type1/7_GP4

/home/rupesh/rupesh/colabfold/SSR1_type1/7_GP4/7/SignalP4_7.csv
Traceback (most recent call last):
  File "/home/rupesh/rupesh/colabfold/GP4_standalone/GP4.py", line 684, in <module>
    with open(outfile_SigP, 'r') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rupesh/rupesh/colabfold/SSR1_type1/7_GP4/7/SignalP4_7.csv'

Please help!

**Comment by grassoste** [comment]
Hi Rupesh

Thanks for using GP4! 

From the error logs looks like SignalP 4 did not produce any output. 

Can you confirm that SignalP 4 works as a standalone on your machine?

**Comment by rupesh-sinha** [comment]
Thanks Stefano,
I checked with SignalP 4 and changed the directory path in the signalp program file  and run it locally and it is able to run locally. But I am getting another error now with SignalP 5 when I run GP4.py as follow:

$ python GP4.py --input /home/rupesh/rupesh/colabfold/SSR1_type1/7.fasta 
/home/rupesh/rupesh/colabfold/GP4_standalone/Results/7_aVMp7/SignalP4_7_aVMp7.csv
Traceback (most recent call last):
  File "/home/rupesh/rupesh/colabfold/GP4_standalone/GP4.py", line 688, in <module>
    with open(results_sigP5, 'r') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rupesh/rupesh/colabfold/GP4_standalone/Results/7_aVMp7/7_aVMp7_summary.signalp5'

I have followed instruction on the SignalP 5.0b.read.me file to copy the 'signalp' file in /usr/local/bin and contents of 'lib' to /usr/local/lib and tried to run it locally like this:

$ signalp -fasta test/euk10.fsa -org euk -format short -prefix euk_10_short
SignalP-5.0. Starting fasta file reading...
Total proteins read: 10.
Organism: euk.
Starting protein prediction...
Temporary directory: /tmp/signalp5.538659136
Protein prediction done!
Generating output files...
Completed.

And it was running fine.

I updated the path in conf.env file in GP4 standalone dir as:

SIGNALP4=/home/rupesh/rupesh/colabfold/signalp-4.1g.Linux/signalp-4.1/signalp
SIGNALP5=/usr/local/bin/signalp
PHOBIUS=/home/rupesh/rupesh/colabfold/phobius101_linux/tmp/tmpaGj9F6/phobius/phobius.pl
LIPOP=/home/rupesh/rupesh/colabfold/lipop-1.0a.Linux/LipoP1.0a/LipoP
TMHMM=/home/rupesh/rupesh/colabfold/tmhmm-2.0c.Linux/tmhmm-2.0c/bin/tmhmm
TATP=/home/rupesh/rupesh/colabfold/tatp-1.0b.Linux/tatp-1.0/tatp
INTERPRO=/home/rupesh/rupesh/colabfold/interproscan-5.33-72.0-64-bit/interproscan-5.33-72.0/interproscan.sh
PERL5LIB=/usr/bin/perl5.34.0

but still I am getting the above mentioned error.

Please help!
